# Generated by Django 6.0.7 on 2026-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="movies_genr_name_850734_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.genre"
            ),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="movies_lang_name_d049f6_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.language"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["name"], name="movies_movi_name_98114c_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["rating"], name="movies_movi_rating_8fd49a_idx"),
        ),
    ]
