# Generated by Django 6.0.7 on 2026-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_genres_language_movie_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
