# Generated by Django 6.0.7 on 2026-08-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_booking_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL or embed link (e.g. https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
